server:
  port: 8080

# for example purposes of Camel version 2.18 and below
baeldung:
  api:
    path: '/camel'

camel:
  springboot:
    # The Camel context name
    name: ServicesRest

    # Configure the underlying Service Call component
 # cloud:
 # service-call:
 #   component: undertow
#
 #   service-filter:
#      blacklist[service-1]: localhost:9012

# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s

# Configure service filter
serviceId: first



weather:
  api:
    url: "https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={key}"
    key: "d363076d55d3ddf7078b8c8f7d9e2ec9"
  service:
    class: "openWeatherService"
